version: "3"

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: rest_template_i:latest
    container_name: rest_template_c
    ports:
      - "8004:8004"
    volumes:
      - ./app:/code
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres_rest_template

  postgres_rest_template:
    image: postgres:latest
    container_name: pg_rest_template_c
    restart: always
    env_file:
      - ./app/config.env
    ports:
      - "8003:8003"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*' -c port=8003

volumes:
  postgres_data:
